FROM microsoft/dotnet:2.1-sdk as builder  

RUN mkdir -p /var/app
WORKDIR /var/app 
COPY ./backend/backend.csproj . 
RUN dotnet restore ./backend.csproj 
COPY ./backend .
RUN dotnet publish -c release -o published 

FROM microsoft/dotnet:2.1-runtime-alpine as runtime

WORKDIR /var
COPY --from=builder /var/app/published .
ENV ASPNETCORE_URLS=http://*:5002
ENV ASPNETCORE_ENVIRONMENT=Production
ENTRYPOINT ["dotnet", "backend.dll"]
